"""
Strait of Hormuz �� Daily Transit Monitor.

An operational dashboard built on IMF PortWatch chokepoint data. Features
KPI cards, date/ship-type filters, a satellite map with port bubbles and
route spokes, and stacked time-series charts with animated date scrubbing.

Data source: IMF PortWatch (https://portwatch.imf.org) — the IMF tracks
global maritime shipping via AIS (Automatic Identification System) satellite
transponders and publishes the data through Esri ArcGIS-hosted APIs. The
Parquet/CSV files in data/ are pre-generated by fetch_data.py.

Three datasets power this dashboard:
  - chokepoint_transits  — daily ship counts through the Strait of Hormuz,
                           by cargo type (tanker, container, dry bulk, etc.)
  - gulf_ports            — static metadata for active ports in the Persian
                           Gulf (name, country, lat/lon, vessel counts)
  - daily_gulf_ports      — daily port-call time series per port

Run with:  streamlit run portwatch/app.py
"""

import json
import math
import time
import urllib.request
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ---------------------------------------------------------------------------
# Paths & constants
# ---------------------------------------------------------------------------

DATA_DIR = Path(__file__).parent / "data"

# Chokepoint transits: daily Hormuz ship counts by cargo type.
# Parquet is preferred (faster); CSV is the fallback for first-run before
# the Parquet cache has been built.
DATA_CSV = DATA_DIR / "chokepoint_transits.csv"
DATA_PARQUET = DATA_DIR / "chokepoint_transits.parquet"

# Port metadata: one row per active Gulf port with location, vessel counts,
# and top industries. Originally queried from IMF PortWatch's ArcGIS
# FeatureServer using a bounding-box spatial filter.
PORTS_CSV = DATA_DIR / "gulf_ports.csv"
PORTS_PARQUET = DATA_DIR / "gulf_ports.parquet"

# Daily port calls: time series of how many ships called at each Gulf port
# per day, broken down by cargo type. Fetched from a separate ArcGIS
# FeatureServer endpoint, one port at a time with pagination.
DAILY_PORTS_PATH = DATA_DIR / "daily_gulf_ports.parquet"

# Approximate centre of the Strait of Hormuz — used for the chokepoint
# marker and as the endpoint of route-spoke lines from Gulf ports.
HORMUZ_LAT, HORMUZ_LON = 26.566, 56.25

# All rolling averages in the dashboard use a fixed 7-day window.
ROLLING_WINDOW = 7

# Colour palette for the six cargo types tracked by IMF PortWatch.
SHIP_TYPE_COLORS = {
    "tanker":        "#ef4444",
    "dry_bulk":      "#a16207",
    "container":     "#3b82f6",
    "gas":           "#eab308",
    "general_cargo": "#14b8a6",
    "ro_ro":         "#a855f7",
}

# One colour per Gulf-region country, chosen to be distinguishable on a
# dark satellite basemap. Used for port bubbles and route spokes.
COUNTRY_COLORS = {
    "Saudi Arabia":         "#166534",
    "United Arab Emirates": "#86efac",
    "Iran":                 "#facc15",
    "Qatar":                "#f97316",
    "Kuwait":               "#92400e",
    "Iraq":                 "#d2b48c",
    "Bahrain":              "#f472b6",
    "Oman":                 "#7dd3fc",
}

# Short legend labels so the horizontal legend fits on one row.
COUNTRY_LABELS = {
    "Saudi Arabia":         "KSA",
    "United Arab Emirates": "UAE",
}

# Maps dashboard cargo-type names to the column names in the daily port
# calls dataset. Only three types have per-port breakdowns.
DAILY_PORT_CARGO_COLS = {
    "tanker":    "portcalls_tanker",
    "container": "portcalls_container",
    "dry_bulk":  "portcalls_dry_bulk",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _lighten(hex_color: str, amount: float = 0.55) -> str:
    """Blend a hex colour toward white by *amount* (0 = original, 1 = white).

    Used for the halo ring behind each port bubble — a light tint of the
    country colour reads better than hard white on the satellite basemap.
    """
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    r = int(r + (255 - r) * amount)
    g = int(g + (255 - g) * amount)
    b = int(b + (255 - b) * amount)
    return f"#{r:02x}{g:02x}{b:02x}"


def _latlon_ring(
    center_lat: float, center_lon: float, radius_deg: float, n: int = 96,
) -> tuple[list[float], list[float]]:
    """Return (lats, lons) for a closed circle on the map.

    Corrects longitude spacing for latitude so the ring looks round on a
    Mercator-style projection. Used for the Hormuz chokepoint glow effect.
    """
    theta = np.linspace(0, 2 * np.pi, n)
    lon_scale = 1.0 / math.cos(math.radians(center_lat))
    lats = (center_lat + radius_deg * np.cos(theta)).tolist()
    lons = (center_lon + radius_deg * np.sin(theta) * lon_scale).tolist()
    return lats, lons


# ---------------------------------------------------------------------------
# Data loading
#
# All loaders use @st.cache_data so the data is read from disk once and
# then served from Streamlit's in-memory cache on every subsequent rerun.
# The ttl (time-to-live) parameter controls how long the cache entry lives
# before Streamlit re-executes the function to pick up any new data.
# ---------------------------------------------------------------------------


@st.cache_data(ttl=86400, show_spinner=False)
def load_coastline_geojson() -> dict:
    """Natural Earth 50m coastline for the map's vector coastline layer.

    Downloaded from GitHub on first run and cached locally so the app
    works offline afterwards. Returns a GeoJSON FeatureCollection dict
    that Plotly's mapbox layer can render directly.
    """
    local = DATA_DIR / "ne_50m_coastline.geojson"
    if not local.exists():
        url = (
            "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
            "master/geojson/ne_50m_coastline.geojson"
        )
        try:
            with urllib.request.urlopen(url, timeout=10) as resp:
                local.write_bytes(resp.read())
        except Exception:
            return {"type": "FeatureCollection", "features": []}
    try:
        return json.loads(local.read_text())
    except Exception:
        return {"type": "FeatureCollection", "features": []}


@st.cache_data(ttl=86400, show_spinner=False)
def load_country_polygons() -> dict[str, dict]:
    """Natural Earth 50m country polygons for the faint per-country fill
    layer on the map.

    Returns a dict like {"Iran": <FeatureCollection>, ...} containing only
    the Gulf-region countries we shade. Splitting per-country at load time
    lets us add one mapbox fill layer per country with its own colour.
    """
    local = DATA_DIR / "ne_50m_admin_0_countries.geojson"
    if not local.exists():
        url = (
            "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
            "master/geojson/ne_50m_admin_0_countries.geojson"
        )
        try:
            with urllib.request.urlopen(url, timeout=15) as resp:
                local.write_bytes(resp.read())
        except Exception:
            return {}
    try:
        full = json.loads(local.read_text())
    except Exception:
        return {}

    # Natural Earth stores country names under different property keys
    # depending on the vintage, so we check multiple fields.
    wanted = set(COUNTRY_COLORS.keys())
    aliases = {
        "United Arab Emirates": {"United Arab Emirates", "UAE"},
        "Saudi Arabia": {"Saudi Arabia"},
    }
    out: dict[str, dict] = {}
    for feat in full.get("features", []):
        props = feat.get("properties", {}) or {}
        names = {props.get("NAME"), props.get("ADMIN"), props.get("NAME_EN")}
        names.discard(None)
        for target in wanted:
            if target in names or names & aliases.get(target, set()):
                out.setdefault(target, {"type": "FeatureCollection", "features": []})
                out[target]["features"].append(feat)
                break
    return out


@st.cache_data(ttl=3600, show_spinner=False)
def _load_daily_ports_cached(mtime: float) -> pd.DataFrame:
    """Load daily port-call data with pre-computed 7-day rolling averages.

    The *mtime* argument is not used inside the function body — it exists
    so that Streamlit's cache key changes when the file is rewritten on
    disk (event-driven invalidation instead of time-based).
    """
    df = pd.read_parquet(DAILY_PORTS_PATH)
    df["date"] = pd.to_datetime(df["date"]).dt.normalize()
    df = df.sort_values(["portid", "date"])
    # Pre-compute rolling averages for each cargo column so map lookups
    # are instant regardless of which ship-type filter is active.
    roll_cols = ["portcalls"] + [c for c in DAILY_PORT_CARGO_COLS.values() if c in df.columns]
    for col in roll_cols:
        df[f"{col}_roll7"] = (
            df.groupby("portid", observed=True)[col]
              .transform(lambda s: s.rolling(7, min_periods=1).mean())
        )
    return df


def load_daily_ports() -> pd.DataFrame:
    """Thin wrapper that guards against a missing file, then passes the
    current mtime into the cached loader for cache invalidation."""
    if not DAILY_PORTS_PATH.exists():
        return pd.DataFrame()
    return _load_daily_ports_cached(DAILY_PORTS_PATH.stat().st_mtime)


@st.cache_data(ttl=3600, show_spinner=False)
def load_ports() -> pd.DataFrame:
    """Load Gulf port metadata. Converts CSV to Parquet on first read
    for faster subsequent loads."""
    if PORTS_PARQUET.exists():
        return pd.read_parquet(PORTS_PARQUET)
    if PORTS_CSV.exists():
        df = pd.read_csv(PORTS_CSV)
        df.to_parquet(PORTS_PARQUET, index=False)
        return df
    return pd.DataFrame()


@st.cache_data(ttl=3600, show_spinner=False)
def load_data() -> pd.DataFrame:
    """Load chokepoint transit data (Parquet preferred, CSV fallback).

    On first run, reads the CSV, filters to Hormuz, narrows dtypes
    (category for strings, int32 for counts), and writes a Parquet file.
    Every run after that short-circuits to the fast Parquet read.
    """
    if DATA_PARQUET.exists():
        return pd.read_parquet(DATA_PARQUET)
    if DATA_CSV.exists():
        df = pd.read_csv(DATA_CSV, parse_dates=["date"])
        df = df[df["chokepoint_name"].str.contains("Hormuz", case=False, na=False)]
        df["cargo_type"] = df["cargo_type"].astype("category")
        df["chokepoint_name"] = df["chokepoint_name"].astype("category")
        df["transits"] = df["transits"].astype("int32")
        df.to_parquet(DATA_PARQUET, index=False)
        return df
    st.error(
        f"No data at `{DATA_CSV}`. Run "
        "`python portwatch/fetch_data.py` to download IMF PortWatch data."
    )
    st.stop()


# ---------------------------------------------------------------------------
# Page config & CSS
#
# set_page_config must be the first Streamlit call. The custom CSS creates
# a dark "operations dashboard" look with a navy background, compact metric
# cards, and colour-coded multiselect chips that match the bar chart.
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Hormuz Transit Monitor",
    layout="wide",
    initial_sidebar_state="collapsed",
)

st.markdown(
    """
    <style>
      [data-testid="stAppViewContainer"] { background: #0b1220 !important; }
      [data-testid="stAppViewContainer"] * { color: #e2e8f0; }
      header[data-testid="stHeader"] { height: 0; min-height: 0; visibility: hidden; }

      .block-container {
          padding: 0 3rem 0.4rem 3rem !important;
          max-width: 100% !important;
      }

      /* Header bar */
      .pw-header {
          background: linear-gradient(90deg, #1e3a8a 0%, #0f172a 100%);
          color: #f8fafc;
          padding: 0.5rem 3rem;
          margin: 0 -3rem 0.7rem -3rem;
          font-size: 1.0rem;
          font-weight: 600;
          letter-spacing: 0.01em;
          border-bottom: 1px solid #1e293b;
          display: grid;
          grid-template-columns: 1fr auto 1fr;
          align-items: center;
      }
      .pw-header .pw-left  { justify-self: start; }
      .pw-header .pw-mid   { justify-self: center; color: #93c5fd; font-weight: 500; font-size: 0.95rem; }
      .pw-header .pw-right { justify-self: end; }

      /* Metric cards — compact grid layout with label on top, value and
         delta side by side on the bottom row. */
      [data-testid="stMetric"] {
          background: #0f172a;
          border: 1px solid #1e293b;
          border-radius: 4px;
          padding: 0.15rem 0.35rem !important;
          min-width: 0 !important;
      }
      [data-testid="stMetric"] > div {
          display: grid !important;
          grid-template-columns: 1fr auto !important;
          grid-template-rows: auto auto !important;
          column-gap: 0.35rem !important;
          align-items: end !important;
          width: 100% !important;
      }
      [data-testid="stMetricLabel"] {
          grid-column: 1 / 3 !important;
          grid-row: 1 !important;
          font-size: 0.55rem !important;
          color: #94a3b8 !important;
          line-height: 1.0 !important;
      }
      [data-testid="stMetricLabel"] p { font-size: 0.55rem !important; }
      [data-testid="stMetricValue"] {
          grid-column: 1 !important;
          grid-row: 2 !important;
          font-size: 0.82rem !important;
          line-height: 1.0 !important;
          color: #f1f5f9 !important;
      }
      [data-testid="stMetricDelta"] {
          grid-column: 2 !important;
          grid-row: 2 !important;
          align-self: end !important;
          white-space: nowrap !important;
          font-size: 0.52rem !important;
          line-height: 1.0 !important;
      }
      [data-testid="stMetricDelta"] svg { width: 0.6rem !important; height: 0.6rem !important; }
      [data-testid="stCaptionContainer"] { margin-top: 0 !important; }

      /* Input widgets */
      [data-baseweb="input"], [data-baseweb="select"] > div { background: #0f172a !important; }
      label[data-baseweb="form-control-label"],
      .stDateInput label, .stMultiSelect label, .stSlider label {
          color: #cbd5e1 !important;
          font-size: 0.72rem !important;
          margin-bottom: 0.1rem !important;
      }
      div[data-testid="stVerticalBlock"] > div { gap: 0.35rem !important; }
      [data-testid="stSlider"] { padding: 0 !important; }
      section[data-testid="stSidebar"] .block-container { padding-top: 1rem !important; }

      /* Ship-type multiselect chips — each chip is coloured to match its
         cargo type in the stacked bar chart. Alphabetical order when all
         are selected: container, dry_bulk, gas, general_cargo, ro_ro, tanker. */
      [data-testid="stMultiSelect"] [data-baseweb="tag"] {
          color: #0b1220 !important;
          border: none !important;
      }
      [data-testid="stMultiSelect"] [data-baseweb="tag"] span,
      [data-testid="stMultiSelect"] [data-baseweb="tag"] div {
          color: inherit !important;
      }
      [data-testid="stMultiSelect"] [data-baseweb="tag"]:nth-of-type(1) { background: #3b82f6 !important; color: #f8fafc !important; }
      [data-testid="stMultiSelect"] [data-baseweb="tag"]:nth-of-type(2) { background: #a16207 !important; color: #f8fafc !important; }
      [data-testid="stMultiSelect"] [data-baseweb="tag"]:nth-of-type(3) { background: #eab308 !important; color: #0b1220 !important; }
      [data-testid="stMultiSelect"] [data-baseweb="tag"]:nth-of-type(4) { background: #14b8a6 !important; color: #0b1220 !important; }
      [data-testid="stMultiSelect"] [data-baseweb="tag"]:nth-of-type(5) { background: #a855f7 !important; color: #f8fafc !important; }
      [data-testid="stMultiSelect"] [data-baseweb="tag"]:nth-of-type(6) { background: #ef4444 !important; color: #f8fafc !important; }

      /* Map border — uses a CSS :has() sibling selector to draw a white
         border around the Plotly map chart without wrapping it in extra HTML. */
      [data-testid="stElementContainer"]:has(.pw-map-anchor) {
          display: none !important;
      }
      [data-testid="stElementContainer"]:has(.pw-map-anchor) + [data-testid="stElementContainer"] {
          border: 2px solid #ffffff !important;
          border-radius: 4px !important;
          padding: 3px !important;
          background: #0b1220 !important;
          box-sizing: border-box !important;
      }

      /* Chart section headings */
      .chart-heading {
          color: #e2e8f0;
          font-size: 1.05rem;
          font-weight: 700;
          letter-spacing: 0.03em;
          text-transform: uppercase;
          text-align: center;
          border-bottom: 1px solid #1e293b;
          padding: 0.15rem 0 0.2rem 0;
          margin: 0.35rem 0 0.3rem 0;
      }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

today_str = date.today().strftime("%A, %d %B %Y")
st.markdown(
    f"<div class='pw-header'>"
    f"<span class='pw-left'>Strait of Hormuz \u00b7 Daily Transit Monitor</span>"
    f"<span class='pw-mid'>{today_str}</span>"
    f"<span class='pw-right'></span>"
    f"</div>",
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Load data
#
# All three loaders are cached — on a warm run these are dict lookups,
# not file reads. The data was originally fetched from IMF PortWatch's
# ArcGIS endpoints by fetch_data.py and saved locally as CSV/Parquet.
# ---------------------------------------------------------------------------

df = load_data()          # chokepoint transits (Hormuz, by cargo type)
ports_df = load_ports()   # static Gulf port metadata
daily_ports = load_daily_ports()  # daily port-call time series

min_d, max_d = df.date.min().date(), df.date.max().date()
default_start = max(min_d, max_d - timedelta(days=365))
ship_types = sorted(df.cargo_type.dropna().unique().tolist())

# ---------------------------------------------------------------------------
# Filters (outside fragment — changes trigger full app rerun)
#
# These live outside the @st.fragment below so that changing the date range
# or ship types triggers a full app rerun, which recomputes the filtered
# DataFrame and aggregates. The animated fragment only needs to handle
# slider movement, not filter changes.
# ---------------------------------------------------------------------------

filter_col_left, filter_col_right = st.columns([1, 1], gap="medium")

with filter_col_left:
    selected_types = st.multiselect("Ship types", options=ship_types, default=ship_types)

with filter_col_right:
    _, centre, _ = st.columns([2, 3, 2], gap="small")
    with centre:
        date_range = st.date_input(
            "Date range",
            value=(default_start, max_d),
            min_value=min_d,
            max_value=max_d,
        )

# Guard against the mid-selection single-date state that st.date_input
# can briefly return while the user is picking the second date.
if isinstance(date_range, tuple) and len(date_range) == 2:
    start, end = date_range
else:
    start, end = default_start, max_d

# Apply both filters to produce the single filtered DataFrame that
# feeds every chart, metric, and map layer below.
mask = (
    (df.date.dt.date >= start)
    & (df.date.dt.date <= end)
    & (df.cargo_type.isin(selected_types))
)
fdf = df.loc[mask].copy()

if fdf.empty:
    st.warning("No rows match the current filters.")
    st.stop()

# ---------------------------------------------------------------------------
# Aggregates (computed once, read by the fragment)
#
# These are derived from the filtered DataFrame and don't change during
# animation — only the selected_day slider position changes. Computing
# them once outside the fragment avoids redundant work on every tick.
# ---------------------------------------------------------------------------

# Daily totals (sum across cargo types) with a 7-day rolling average.
daily = (
    fdf.groupby("date", as_index=False)["transits"]
    .sum()
    .sort_values("date")
    .reset_index(drop=True)
)
daily["rolling"] = daily["transits"].rolling(ROLLING_WINDOW, min_periods=1).mean()

# Pivot table for the per-day cargo breakdown shown in hover tooltips.
# Each day's tooltip contains a monospaced bar chart of transit counts
# by cargo type, rendered as Unicode block characters.
day_pivot = fdf.pivot_table(
    index="date", columns="cargo_type", values="transits",
    aggfunc="sum", fill_value=0, observed=True,
)
cargo_order = day_pivot.sum(axis=0).sort_values(ascending=False).index.tolist()
day_pivot = day_pivot[cargo_order]
bar_max = float(day_pivot.to_numpy().max()) or 1.0
BAR_WIDTH = 10
LABEL_WIDTH = max((len(c) for c in cargo_order), default=8) + 2


def _breakdown_text(row: pd.Series) -> str:
    """Build a monospaced per-cargo-type bar chart for a single day's hover."""
    lines = []
    for col in cargo_order:
        val = int(row[col])
        filled = int(round(BAR_WIDTH * val / bar_max))
        bar = ("\u2588" * filled).ljust(BAR_WIDTH)
        lines.append(f"{col:<{LABEL_WIDTH}}{bar} {val:>4}")
    return "<br>".join(lines)


daily["breakdown"] = daily["date"].map(
    lambda d: _breakdown_text(day_pivot.loc[d]) if d in day_pivot.index else ""
)

# Summary stats for the KPI cards.
latest_val = float(daily["transits"].iloc[-1])
avg_7 = float(daily["transits"].tail(7).mean())
avg_30 = float(daily["transits"].tail(30).mean())

# Year-ago comparison: average of a +/-3 day window around the same date
# last year, to smooth out day-of-week effects.
latest_date = daily["date"].iloc[-1]
ya_target = latest_date - pd.Timedelta(days=365)
ya_window = daily[
    (daily.date >= ya_target - pd.Timedelta(days=3))
    & (daily.date <= ya_target + pd.Timedelta(days=3))
]
year_ago = float(ya_window["transits"].mean()) if not ya_window.empty else float("nan")

slider_min = daily["date"].iloc[0].to_pydatetime()
slider_max = daily["date"].iloc[-1].to_pydatetime()

# Pre-grouped data for the stacked bar chart.
by_type = fdf.groupby(["date", "cargo_type"], as_index=False, observed=True)["transits"].sum()


# ---------------------------------------------------------------------------
# Animated dashboard fragment
#
# @st.fragment isolates this section: when the play button is active,
# st.rerun() at the bottom only reruns this function, not the entire app.
# The header, CSS, filters, and aggregates above stay frozen, so only
# the map, charts, and KPIs re-render on each animation tick (~150ms).
# ---------------------------------------------------------------------------

@st.fragment
def render_dashboard():
    # --- Animation state ---
    SLIDER_KEY = "map_date_slider"
    if SLIDER_KEY not in st.session_state:
        st.session_state[SLIDER_KEY] = slider_max
    if "playing" not in st.session_state:
        st.session_state.playing = False

    # Clamp slider to current filter bounds (in case the user narrowed
    # the date range while animation was running).
    st.session_state[SLIDER_KEY] = max(slider_min, min(slider_max, st.session_state[SLIDER_KEY]))

    # Advance one day per tick when playing; wrap around at the end.
    if st.session_state.playing and slider_min != slider_max:
        nxt = st.session_state[SLIDER_KEY] + timedelta(days=1)
        st.session_state[SLIDER_KEY] = nxt if nxt <= slider_max else slider_min

    # --- Two-column layout: map on the left, charts on the right ---
    map_col, chart_col = st.columns([1, 1], gap="medium")

    # --- Charts (right column) ---
    with chart_col:
        # Play/pause button + date slider.
        if slider_min == slider_max:
            selected_day = slider_max
        else:
            play_col, slider_col = st.columns([1, 10], gap="small")
            with play_col:
                label = "\u23f8" if st.session_state.playing else "\u25b6"
                if st.button(label, key="play_btn", use_container_width=True,
                             help="Auto-advance the map date"):
                    st.session_state.playing = not st.session_state.playing
                    st.rerun()
            with slider_col:
                selected_day = st.slider(
                    "Map date",
                    min_value=slider_min,
                    max_value=slider_max,
                    format="YYYY-MM-DD",
                    step=timedelta(days=1),
                    key=SLIDER_KEY,
                    label_visibility="collapsed",
                )

        st.markdown(
            "<div class='chart-heading'>Daily transits through Hormuz</div>",
            unsafe_allow_html=True,
        )

        # Look up metrics for the currently selected day.
        selected_day_ts = pd.Timestamp(selected_day).normalize()
        day_row = daily[daily["date"] == selected_day_ts]
        day_val = float(day_row["transits"].iloc[0]) if not day_row.empty else 0.0
        day_rolling = float(day_row["rolling"].iloc[0]) if not day_row.empty else 0.0
        total_transits = int(fdf["transits"].sum())
        days_covered = int(daily.shape[0])

        x_min, x_max = daily["date"].min(), daily["date"].max()

        # Time-series line chart: daily counts + 7-day rolling average.
        # The red dotted vertical line marks the currently selected day.
        # Hovering over a point shows a monospaced per-cargo-type breakdown.
        fig_ts = px.line(
            daily, x="date", y=["transits", "rolling"],
            labels={"value": "Transits / day", "date": "", "variable": ""},
        )
        fig_ts.data[0].name = "Daily"
        fig_ts.data[0].mode = "lines+markers"
        fig_ts.data[0].marker = dict(size=5, color="#60a5fa")
        fig_ts.data[0].customdata = daily["breakdown"].to_numpy().reshape(-1, 1)
        fig_ts.data[0].hovertemplate = (
            "<b>%{x|%Y-%m-%d}</b>  \u00b7  %{y:.0f} transits<br>"
            "<span style='color:#94a3b8'>\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500</span><br>"
            "%{customdata[0]}<extra></extra>"
        )
        fig_ts.data[1].name = f"{ROLLING_WINDOW}-day avg"
        fig_ts.data[1].hovertemplate = (
            "%{x|%Y-%m-%d}<br>%{y:.1f}<extra>%{fullData.name}</extra>"
        )
        fig_ts.add_vline(x=selected_day_ts, line_width=1, line_dash="dot", line_color="#f87171")
        fig_ts.update_layout(
            height=185,
            margin=dict(l=52, r=12, t=5, b=20),
            paper_bgcolor="#0b1220",
            plot_bgcolor="#0b1220",
            font=dict(color="#cbd5e1", size=11),
            xaxis=dict(
                gridcolor="#1e293b", showgrid=True,
                tickfont=dict(size=12, color="#e2e8f0"),
                tickformat="%b %Y", nticks=6,
                range=[x_min, x_max],
            ),
            yaxis=dict(gridcolor="#1e293b", showgrid=True, title=None, tickfont=dict(size=11)),
            legend=dict(orientation="h", y=1.2, x=1, xanchor="right", font=dict(size=10)),
            # Monospace hover font so the per-day bar chart aligns.
            hoverlabel=dict(
                bgcolor="#0f172a", bordercolor="#475569",
                font=dict(family="Courier New, monospace", size=12, color="#e2e8f0"),
                align="left",
            ),
        )
        st.plotly_chart(
            fig_ts, use_container_width=True, key="ts_chart",
            config={"displayModeBar": False, "scrollZoom": False},
        )

        # Stacked bar chart: daily transits broken down by cargo type.
        # Same x-axis range and red vline as the line chart above so
        # they line up vertically.
        st.markdown(
            "<div class='chart-heading'>Transits by cargo type</div>",
            unsafe_allow_html=True,
        )

        fig_bar = px.bar(
            by_type, x="date", y="transits", color="cargo_type",
            color_discrete_map=SHIP_TYPE_COLORS,
            labels={"transits": "Transits", "date": "", "cargo_type": "Ship type"},
        )
        fig_bar.add_vline(x=selected_day_ts, line_width=1, line_dash="dot", line_color="#f87171")
        fig_bar.update_layout(
            height=185,
            margin=dict(l=52, r=12, t=5, b=20),
            paper_bgcolor="#0b1220",
            plot_bgcolor="#0b1220",
            font=dict(color="#cbd5e1", size=11),
            xaxis=dict(
                gridcolor="#1e293b", showgrid=False,
                tickfont=dict(size=12, color="#e2e8f0"),
                tickformat="%b %Y", nticks=6,
                range=[x_min, x_max],
            ),
            yaxis=dict(gridcolor="#1e293b", showgrid=True, title=None, tickfont=dict(size=11)),
            barmode="stack",
            legend=dict(
                orientation="h", y=1.4, x=1, xanchor="right",
                font=dict(size=10, color="#f8fafc"), title=None,
            ),
        )
        st.plotly_chart(fig_bar, use_container_width=True, config={"displayModeBar": False})

    # --- Map (left column) ---
    #
    # The map uses Plotly's Scattermapbox on a "carto-darkmatter" basemap
    # with layered raster tiles (Esri satellite imagery + reference labels),
    # vector coastlines (Natural Earth), and faint per-country fills.
    # Port bubbles are sized by a 7-day rolling average of port calls for
    # the selected cargo types on the selected day.
    with map_col:
        st.markdown("<div style='height: 1.95rem'></div>", unsafe_allow_html=True)
        # Hidden anchor element — CSS uses :has() to target the next sibling
        # (the map) and draw a white border around it.
        st.markdown("<span class='pw-map-anchor'></span>", unsafe_allow_html=True)

        fig_map = go.Figure()

        # --- Port bubbles & route spokes ---
        if not ports_df.empty:
            # Compute the metric that sizes each port bubble: the 7-day
            # rolling average of port calls for the selected cargo types
            # on the selected day. Falls back to all-time vessel count
            # if daily data isn't available.
            if not daily_ports.empty:
                available = set(DAILY_PORT_CARGO_COLS)
                matched = set(selected_types) & available
                day_frame = daily_ports[daily_ports["date"] == selected_day_ts]
                if matched:
                    sum_cols = [f"{DAILY_PORT_CARGO_COLS[t]}_roll7" for t in matched]
                    day_snapshot = day_frame.set_index("portid")[sum_cols].sum(axis=1)
                else:
                    day_snapshot = day_frame.set_index("portid")["portcalls_roll7"] * 0.0
                port_metric = ports_df["portid"].map(day_snapshot).fillna(0.0).to_numpy()
            else:
                port_metric = ports_df["vessel_count_total"].fillna(0).to_numpy()

            # Bubble sizes: sqrt-scaled so area is proportional to the metric.
            max_metric = max(float(port_metric.max()), 1.0)
            sizes = 5.0 + 26.0 * np.sqrt(port_metric / max_metric)

            ports_plot = ports_df.reset_index(drop=True).copy()
            ports_plot["_metric"] = port_metric
            ports_plot["_size"] = sizes

            # Only label the top 10 ports by metric to avoid clutter.
            top_idx = set(np.argsort(-port_metric)[:10].tolist())
            ports_plot["_label"] = [
                row["portname"] if i in top_idx else ""
                for i, row in ports_plot.iterrows()
            ]

            # Route spokes: one line per Gulf-side port to the Hormuz
            # chokepoint, width scaled by the port's metric and coloured
            # by country. Only ports west of Hormuz (lon < 56.3) get spokes.
            gulf = ports_plot[ports_plot["lon"] < 56.3]
            for _, row in gulf.iterrows():
                width = 0.6 + 5.5 * np.sqrt(float(row["_metric"]) / max_metric)
                colour = COUNTRY_COLORS.get(row["country"], "#94a3b8")
                fig_map.add_trace(go.Scattermapbox(
                    lat=[row["lat"], HORMUZ_LAT],
                    lon=[row["lon"], HORMUZ_LON],
                    mode="lines",
                    line=dict(color=colour, width=width),
                    opacity=0.65,
                    hoverinfo="skip",
                    showlegend=False,
                ))

            # One trace per country for port markers, so the legend groups
            # by country. Rendered in a stable order (COUNTRY_COLORS dict
            # order first, then any countries not in the palette).
            country_order = [c for c in COUNTRY_COLORS if c in ports_plot["country"].unique()]
            country_order += [
                c for c in ports_plot["country"].dropna().unique()
                if c not in COUNTRY_COLORS
            ]

            # Halo ring: a slightly larger, lighter dot behind each bubble
            # to fake an outline stroke (Scattermapbox doesn't support
            # marker.line like regular Scatter).
            for country in country_order:
                group = ports_plot[ports_plot["country"] == country]
                if group.empty:
                    continue
                halo_colour = _lighten(COUNTRY_COLORS.get(country, "#94a3b8"), 0.55)
                fig_map.add_trace(go.Scattermapbox(
                    lat=group["lat"], lon=group["lon"],
                    mode="markers",
                    marker=dict(size=(group["_size"] + 2.6).tolist(), color=halo_colour, opacity=0.95),
                    hoverinfo="skip", showlegend=False,
                ))

            # Coloured port bubbles with hover tooltips.
            for country in country_order:
                group = ports_plot[ports_plot["country"] == country]
                if group.empty:
                    continue
                colour = COUNTRY_COLORS.get(country, "#94a3b8")
                customdata = list(zip(
                    group["portname"].fillna("\u2014"),
                    group["country"].fillna("\u2014"),
                    group["_metric"],
                    group["vessel_count_total"].fillna(0).astype(int),
                    group["industry_top1"].fillna("\u2014"),
                ))
                fig_map.add_trace(go.Scattermapbox(
                    lat=group["lat"], lon=group["lon"],
                    text=group["_label"],
                    customdata=customdata,
                    mode="markers+text",
                    textposition="top right",
                    textfont=dict(color="#f8fafc", size=11),
                    marker=dict(size=group["_size"].tolist(), color=colour, opacity=0.95),
                    name=COUNTRY_LABELS.get(country, country),
                    legendgroup=country,
                    hovertemplate=(
                        "<b>%{customdata[0]}</b> \u2014 %{customdata[1]}<br>"
                        "Port calls (7-day avg): %{customdata[2]:.1f}<br>"
                        "All-time vessel count: %{customdata[3]:,}<br>"
                        "Top industry: %{customdata[4]}<extra></extra>"
                    ),
                ))

        # --- Hormuz chokepoint marker ---
        # Built from multiple layers to create a glowing bullseye effect:
        # soft radial glow halos, concentric ring lines, and a layered
        # centre dot that scales with the day's transit volume.

        # Soft glow: filled circles at increasing radii, darkest outside.
        glow_layers = [
            (1.30, "rgba(69, 10, 10, 0.05)"),
            (1.05, "rgba(127, 29, 29, 0.07)"),
            (0.82, "rgba(185, 28, 28, 0.09)"),
            (0.62, "rgba(220, 38, 38, 0.12)"),
            (0.44, "rgba(239, 68, 68, 0.16)"),
        ]
        for radius_deg, rgba in glow_layers:
            g_lats, g_lons = _latlon_ring(HORMUZ_LAT, HORMUZ_LON, radius_deg)
            fig_map.add_trace(go.Scattermapbox(
                lat=g_lats, lon=g_lons, mode="lines",
                fill="toself", fillcolor=rgba, line=dict(width=0, color=rgba),
                hoverinfo="skip", showlegend=False,
            ))

        # Concentric rings: crimson -> red -> orange toward the centre.
        for radius_deg, color, width in [
            (0.48, "#991b1b", 1.2),
            (0.30, "#ef4444", 1.8),
            (0.15, "#f97316", 2.4),
        ]:
            r_lats, r_lons = _latlon_ring(HORMUZ_LAT, HORMUZ_LON, radius_deg)
            fig_map.add_trace(go.Scattermapbox(
                lat=r_lats, lon=r_lons, mode="lines",
                line=dict(width=width, color=color),
                hoverinfo="skip", showlegend=False,
            ))

        # Centre dots: three markers at the same lat/lon with decreasing
        # size and increasing brightness (deep red -> orange -> white-hot).
        # The innermost dot carries the hover tooltip.
        core_size = max(6, min(14, 4 + day_val * 0.10))
        for size_mult, color, opacity in [
            (2.10, "#dc2626", 0.38),
            (1.55, "#f97316", 0.55),
            (1.00, "#fff7ed", 0.85),
        ]:
            is_core = size_mult == 1.00
            fig_map.add_trace(go.Scattermapbox(
                lat=[HORMUZ_LAT], lon=[HORMUZ_LON], mode="markers",
                marker=dict(size=core_size * size_mult, color=color, opacity=opacity),
                name="Hormuz chokepoint" if is_core else None,
                showlegend=False,
                hoverinfo="skip" if not is_core else None,
                hovertemplate=(
                    "<b>Strait of Hormuz</b><br>"
                    f"{selected_day_ts.date()}: {day_val:.0f} transits<br>"
                    f"{ROLLING_WINDOW}-day avg: {day_rolling:.1f}<br>"
                    f"Filter total: {total_transits:,} over {days_covered} days"
                    "<extra></extra>"
                ) if is_core else None,
            ))

        # --- Map layout ---
        # Basemap layers stacked bottom to top:
        #   1. Esri satellite imagery (low opacity for a dark look)
        #   2. Translucent blue wash to darken the satellite tiles further
        #   3. Esri reference tiles (country borders + place labels)
        #   4. Natural Earth vector coastline for crisp land/water edges
        #   5. Per-country tinted fills for geographic context
        fig_map.update_layout(
            mapbox=dict(
                style="carto-darkmatter",
                layers=[
                    {
                        "below": "traces",
                        "sourcetype": "raster",
                        "sourceattribution": "Esri, Maxar, Earthstar Geographics",
                        "source": [
                            "https://server.arcgisonline.com/ArcGIS/rest/services/"
                            "World_Imagery/MapServer/tile/{z}/{y}/{x}"
                        ],
                        "opacity": 0.38,
                    },
                    {
                        "below": "traces",
                        "sourcetype": "geojson",
                        "type": "fill",
                        "color": "#0b1a3a",
                        "opacity": 0.35,
                        "source": {
                            "type": "Feature",
                            "geometry": {
                                "type": "Polygon",
                                "coordinates": [[[20, -10], [80, -10], [80, 50], [20, 50], [20, -10]]],
                            },
                        },
                    },
                    {
                        "below": "traces",
                        "sourcetype": "raster",
                        "source": [
                            "https://server.arcgisonline.com/ArcGIS/rest/services/"
                            "Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}"
                        ],
                        "opacity": 0.85,
                    },
                    {
                        "below": "traces",
                        "sourcetype": "geojson",
                        "type": "line",
                        "color": "#f8fafc",
                        "opacity": 0.9,
                        "line": {"width": 1.2},
                        "source": load_coastline_geojson(),
                    },
                    *[
                        {
                            "below": "traces",
                            "sourcetype": "geojson",
                            "type": "fill",
                            "color": COUNTRY_COLORS[country],
                            "opacity": 0.10,
                            "source": geojson,
                        }
                        for country, geojson in load_country_polygons().items()
                        if country in COUNTRY_COLORS
                    ],
                ],
                center=dict(lat=25.5, lon=55.0),
                zoom=4.4,
            ),
            height=420,
            margin=dict(l=0, r=0, t=0, b=24),
            paper_bgcolor="#0b1220",
            plot_bgcolor="#0b1220",
            showlegend=True,
            legend=dict(
                orientation="h",
                x=0.5, y=-0.02, xanchor="center", yanchor="top",
                bgcolor="rgba(11,18,32,0.0)",
                bordercolor="#334155", borderwidth=0,
                font=dict(color="#e2e8f0", size=9),
                itemsizing="constant", itemwidth=30, tracegroupgap=2,
                title=dict(text="", font=dict(size=9, color="#cbd5e1")),
            ),
        )
        st.plotly_chart(
            fig_map, use_container_width=True,
            config={
                "scrollZoom": True,
                "displayModeBar": True,
                "displaylogo": False,
                "modeBarButtonsToRemove": ["lasso2d", "select2d"],
                "doubleClick": "reset",
            },
        )

        # --- KPI cards ---
        st.markdown("<div class='pw-mini-metrics'>", unsafe_allow_html=True)
        mk1, mk2, mk3, mk4 = st.columns(4, gap="small")
        mk1.metric(f"{selected_day_ts.date()}", f"{day_val:.0f}", delta=f"{day_val - avg_7:+.0f}")
        mk2.metric("7-day avg", f"{avg_7:.1f}")
        mk3.metric("30-day avg", f"{avg_30:.1f}")
        if pd.isna(year_ago) or year_ago == 0:
            mk4.metric("Year-ago", "\u2014")
        else:
            mk4.metric("Year-ago", f"{year_ago:.1f}", delta=f"{((latest_val / year_ago) - 1) * 100:+.1f}%")
        st.markdown("</div>", unsafe_allow_html=True)

    # --- Animation tick ---
    # When playing, sleep briefly then rerun this fragment (not the whole
    # app). The rerun lands back at the top of this function, which
    # advances the slider by one day and rebuilds the visuals.
    if st.session_state.get("playing", False):
        time.sleep(0.15)
        st.rerun()


render_dashboard()
