"""
Hormuz Transit Monitor — basic version.

Minimal Streamlit dashboard showing the core building blocks:
page config, cached data loading, sidebar filters, KPI metrics,
a Plotly chart, and a simple map.

Data source: IMF PortWatch (https://portwatch.imf.org) — daily ship
transit counts through the Strait of Hormuz, broken down by cargo type.
The Parquet files are pre-generated by fetch_data.py, which pulls from
ArcGIS-hosted IMF APIs.

Run with:  streamlit run portwatch/app_basic.py
"""

from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st

# ---------------------------------------------------------------------------
# Paths
#
# Both files are Parquet (columnar, compressed) — converted from the raw
# CSV/JSON that fetch_data.py downloads from IMF PortWatch's ArcGIS APIs.
# Parquet reads ~10x faster than CSV for this size of data.
# ---------------------------------------------------------------------------

DATA_PATH = Path(__file__).parent / "data" / "chokepoint_transits.parquet"
PORTS_PATH = Path(__file__).parent / "data" / "gulf_ports.parquet"

# ---------------------------------------------------------------------------
# Page config (must be the first Streamlit call)
# ---------------------------------------------------------------------------

st.set_page_config(page_title="Hormuz Monitor (basic)", layout="wide")

# ---------------------------------------------------------------------------
# Data loading
#
# @st.cache_data memoises the return value: Streamlit reruns this whole
# file top-to-bottom on every widget interaction, but the cached function
# body only executes once. Subsequent runs return the cached DataFrame
# instantly, avoiding repeated disk reads.
# ---------------------------------------------------------------------------


@st.cache_data
def load_transits() -> pd.DataFrame:
    """Daily transit counts through the Strait of Hormuz by cargo type.

    Schema: date | chokepoint_name | cargo_type | transits
    One row per (date, cargo_type). Originally sourced from the IMF
    PortWatch chokepoint dataset on ArcGIS Hub.
    """
    return pd.read_parquet(DATA_PATH)


@st.cache_data
def load_ports() -> pd.DataFrame:
    """Static metadata for active ports in the Persian Gulf region.

    Schema: portid | portname | country | lat | lon | vessel_count_* | ...
    Queried from the IMF PortWatch ports FeatureServer via a bounding-box
    spatial filter covering the Gulf, Gulf of Oman, and Strait of Hormuz.
    """
    return pd.read_parquet(PORTS_PATH)


df = load_transits()
ports = load_ports()

# ---------------------------------------------------------------------------
# Sidebar filters
#
# Widgets return plain Python values. Streamlit's reactive model means
# that changing any widget automatically reruns the script with the new
# values, so the chart and KPIs below always reflect the current filters.
# ---------------------------------------------------------------------------

st.sidebar.header("Filters")

min_date, max_date = df["date"].min().date(), df["date"].max().date()
start, end = st.sidebar.date_input(
    "Date range",
    value=(max_date - pd.Timedelta(days=30), max_date),
    min_value=min_date,
    max_value=max_date,
)

cargo_types = sorted(df["cargo_type"].unique())
selected = st.sidebar.multiselect("Cargo types", cargo_types, default=cargo_types)

# "Filter upstream of views" pattern: one filtered DataFrame feeds every
# chart and metric below, so there's a single source of truth for what
# the user is looking at.
mask = (
    (df["date"] >= pd.Timestamp(start))
    & (df["date"] <= pd.Timestamp(end))
    & (df["cargo_type"].isin(selected))
)
view = df.loc[mask]

# ---------------------------------------------------------------------------
# KPIs
#
# st.metric renders a big number with an optional delta indicator.
# st.columns splits the page into side-by-side containers.
# ---------------------------------------------------------------------------

st.title("Strait of Hormuz — Transit Monitor")

col1, col2, col3 = st.columns(3)
col1.metric("Total transits", f"{view['transits'].sum():,}")
col2.metric("Avg / day", f"{view.groupby('date')['transits'].sum().mean():,.0f}")
col3.metric("Days in view", view["date"].nunique())

# ---------------------------------------------------------------------------
# Chart
#
# Plotly Express builds figures from DataFrames in one call. The stacked
# area chart shows how each cargo type contributes to total daily volume.
# use_container_width=True makes it fill the Streamlit column.
# ---------------------------------------------------------------------------

daily = view.groupby(["date", "cargo_type"], observed=True)["transits"].sum().reset_index()
fig = px.area(daily, x="date", y="transits", color="cargo_type",
              title="Daily transits by cargo type")
st.plotly_chart(fig, use_container_width=True)

# ---------------------------------------------------------------------------
# Map
#
# st.map is Streamlit's simplest mapping primitive — it expects a DataFrame
# with "lat" and "lon" columns and drops a dot for each row. The gulf_ports
# data already has these columns from the IMF PortWatch port metadata.
# ---------------------------------------------------------------------------

st.subheader("Gulf ports")
st.map(ports[["lat", "lon"]])
